-- +goose Up

-- Project Memberships
CREATE TABLE project_memberships (
    -- Identification
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    role VARCHAR(256) NOT NULL, -- e.g. 'owner', 'admin', 'member'

    -- Relations
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    
    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    
    UNIQUE(project_id, user_id)
);

-- Permissions (Pre-seeded via keys)
CREATE TABLE permissions (
    -- Identification
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    key VARCHAR(256) NOT NULL UNIQUE, -- e.g. 'application.create'

    -- Information
    description TEXT
);

-- User/Member Project Permissions (Many-to-Many)
CREATE TABLE membership_permissions (
    -- Relations
    membership_id UUID NOT NULL REFERENCES project_memberships(id) ON DELETE CASCADE,
    permission_id INTEGER NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (membership_id, permission_id)
);

-- +goose Down
DROP TABLE IF EXISTS membership_permissions;
DROP TABLE IF EXISTS permissions;
DROP TABLE IF EXISTS project_memberships;
