// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: applications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (
    title,
    package_name,
    description,
    project_id
) VALUES (
    $1, $2, $3, $4
) RETURNING id, title, package_name, description, project_id, created_at, updated_at, deleted_at
`

type CreateApplicationParams struct {
	Title       string      `json:"title"`
	PackageName string      `json:"package_name"`
	Description pgtype.Text `json:"description"`
	ProjectID   pgtype.UUID `json:"project_id"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.Title,
		arg.PackageName,
		arg.Description,
		arg.ProjectID,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.PackageName,
		&i.Description,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getApplicationByID = `-- name: GetApplicationByID :one
SELECT id, title, package_name, description, project_id, created_at, updated_at, deleted_at FROM applications 
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetApplicationByID(ctx context.Context, id pgtype.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByID, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.PackageName,
		&i.Description,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getApplicationByPackageName = `-- name: GetApplicationByPackageName :one
SELECT id, title, package_name, description, project_id, created_at, updated_at, deleted_at FROM applications 
WHERE package_name = $1 AND deleted_at IS NULL
`

func (q *Queries) GetApplicationByPackageName(ctx context.Context, packageName string) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByPackageName, packageName)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.PackageName,
		&i.Description,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteApplication = `-- name: HardDeleteApplication :exec
DELETE FROM applications WHERE id = $1
`

func (q *Queries) HardDeleteApplication(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteApplication, id)
	return err
}

const listApplicationsByProject = `-- name: ListApplicationsByProject :many
SELECT id, title, package_name, description, project_id, created_at, updated_at, deleted_at FROM applications 
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListApplicationsByProject(ctx context.Context, projectID pgtype.UUID) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplicationsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.PackageName,
			&i.Description,
			&i.ProjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteApplication = `-- name: SoftDeleteApplication :one
UPDATE applications SET
    deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, title, package_name, description, project_id, created_at, updated_at, deleted_at
`

func (q *Queries) SoftDeleteApplication(ctx context.Context, id pgtype.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, softDeleteApplication, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.PackageName,
		&i.Description,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateApplication = `-- name: UpdateApplication :one
UPDATE applications SET
    title = $2,
    description = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, title, package_name, description, project_id, created_at, updated_at, deleted_at
`

type UpdateApplicationParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplication, arg.ID, arg.Title, arg.Description)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.PackageName,
		&i.Description,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
