// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artifacts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts (
    file_url,
    sha256_hash,
    file_size,
    file_type,
    abi,
    release_id
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, file_url, sha256_hash, file_size, file_type, abi, release_id, created_at, updated_at, deleted_at
`

type CreateArtifactParams struct {
	FileUrl    string      `json:"file_url"`
	Sha256Hash string      `json:"sha256_hash"`
	FileSize   int64       `json:"file_size"`
	FileType   string      `json:"file_type"`
	Abi        pgtype.Text `json:"abi"`
	ReleaseID  pgtype.UUID `json:"release_id"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.FileUrl,
		arg.Sha256Hash,
		arg.FileSize,
		arg.FileType,
		arg.Abi,
		arg.ReleaseID,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.FileUrl,
		&i.Sha256Hash,
		&i.FileSize,
		&i.FileType,
		&i.Abi,
		&i.ReleaseID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getArtifactByID = `-- name: GetArtifactByID :one
SELECT id, file_url, sha256_hash, file_size, file_type, abi, release_id, created_at, updated_at, deleted_at FROM artifacts 
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetArtifactByID(ctx context.Context, id pgtype.UUID) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifactByID, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.FileUrl,
		&i.Sha256Hash,
		&i.FileSize,
		&i.FileType,
		&i.Abi,
		&i.ReleaseID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getArtifactByReleaseAndABI = `-- name: GetArtifactByReleaseAndABI :one
SELECT id, file_url, sha256_hash, file_size, file_type, abi, release_id, created_at, updated_at, deleted_at FROM artifacts 
WHERE release_id = $1 AND abi = $2 AND deleted_at IS NULL
`

type GetArtifactByReleaseAndABIParams struct {
	ReleaseID pgtype.UUID `json:"release_id"`
	Abi       pgtype.Text `json:"abi"`
}

func (q *Queries) GetArtifactByReleaseAndABI(ctx context.Context, arg GetArtifactByReleaseAndABIParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifactByReleaseAndABI, arg.ReleaseID, arg.Abi)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.FileUrl,
		&i.Sha256Hash,
		&i.FileSize,
		&i.FileType,
		&i.Abi,
		&i.ReleaseID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteArtifact = `-- name: HardDeleteArtifact :exec
DELETE FROM artifacts WHERE id = $1
`

func (q *Queries) HardDeleteArtifact(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteArtifact, id)
	return err
}

const listArtifactsByRelease = `-- name: ListArtifactsByRelease :many
SELECT id, file_url, sha256_hash, file_size, file_type, abi, release_id, created_at, updated_at, deleted_at FROM artifacts 
WHERE release_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ListArtifactsByRelease(ctx context.Context, releaseID pgtype.UUID) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsByRelease, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.FileUrl,
			&i.Sha256Hash,
			&i.FileSize,
			&i.FileType,
			&i.Abi,
			&i.ReleaseID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteArtifact = `-- name: SoftDeleteArtifact :one
UPDATE artifacts SET
    deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, file_url, sha256_hash, file_size, file_type, abi, release_id, created_at, updated_at, deleted_at
`

func (q *Queries) SoftDeleteArtifact(ctx context.Context, id pgtype.UUID) (Artifact, error) {
	row := q.db.QueryRow(ctx, softDeleteArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.FileUrl,
		&i.Sha256Hash,
		&i.FileSize,
		&i.FileType,
		&i.Abi,
		&i.ReleaseID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
