// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ProjectInviteStatus string

const (
	ProjectInviteStatusPENDING   ProjectInviteStatus = "PENDING"
	ProjectInviteStatusACCEPTED  ProjectInviteStatus = "ACCEPTED"
	ProjectInviteStatusREJECTED  ProjectInviteStatus = "REJECTED"
	ProjectInviteStatusCANCELLED ProjectInviteStatus = "CANCELLED"
)

func (e *ProjectInviteStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectInviteStatus(s)
	case string:
		*e = ProjectInviteStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectInviteStatus: %T", src)
	}
	return nil
}

type NullProjectInviteStatus struct {
	ProjectInviteStatus ProjectInviteStatus `json:"project_invite_status"`
	Valid               bool                `json:"valid"` // Valid is true if ProjectInviteStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectInviteStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectInviteStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectInviteStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectInviteStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectInviteStatus), nil
}

type ReleaseEnvironment string

const (
	ReleaseEnvironmentDevelopment ReleaseEnvironment = "development"
	ReleaseEnvironmentStaging     ReleaseEnvironment = "staging"
	ReleaseEnvironmentProduction  ReleaseEnvironment = "production"
)

func (e *ReleaseEnvironment) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReleaseEnvironment(s)
	case string:
		*e = ReleaseEnvironment(s)
	default:
		return fmt.Errorf("unsupported scan type for ReleaseEnvironment: %T", src)
	}
	return nil
}

type NullReleaseEnvironment struct {
	ReleaseEnvironment ReleaseEnvironment `json:"release_environment"`
	Valid              bool               `json:"valid"` // Valid is true if ReleaseEnvironment is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReleaseEnvironment) Scan(value interface{}) error {
	if value == nil {
		ns.ReleaseEnvironment, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReleaseEnvironment.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReleaseEnvironment) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReleaseEnvironment), nil
}

type Application struct {
	ID          pgtype.UUID      `json:"id"`
	Title       string           `json:"title"`
	PackageName string           `json:"package_name"`
	Description pgtype.Text      `json:"description"`
	ProjectID   pgtype.UUID      `json:"project_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
}

type ApplicationRelease struct {
	ID            pgtype.UUID        `json:"id"`
	Title         string             `json:"title"`
	VersionCode   int32              `json:"version_code"`
	VersionName   string             `json:"version_name"`
	ReleaseNote   pgtype.Text        `json:"release_note"`
	Environment   ReleaseEnvironment `json:"environment"`
	ApplicationID pgtype.UUID        `json:"application_id"`
	CreatedAt     pgtype.Timestamp   `json:"created_at"`
	UpdatedAt     pgtype.Timestamp   `json:"updated_at"`
	DeletedAt     pgtype.Timestamp   `json:"deleted_at"`
}

type Artifact struct {
	ID         pgtype.UUID      `json:"id"`
	FileUrl    string           `json:"file_url"`
	Sha256Hash string           `json:"sha256_hash"`
	FileSize   int64            `json:"file_size"`
	FileType   string           `json:"file_type"`
	Abi        pgtype.Text      `json:"abi"`
	ReleaseID  pgtype.UUID      `json:"release_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
}

type Project struct {
	ID          pgtype.UUID      `json:"id"`
	Title       string           `json:"title"`
	Description string           `json:"description"`
	OwnerID     pgtype.UUID      `json:"owner_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
}

type ProjectInvite struct {
	ID            pgtype.UUID         `json:"id"`
	Status        ProjectInviteStatus `json:"status"`
	CreatedAt     pgtype.Timestamp    `json:"created_at"`
	UpdatedAt     pgtype.Timestamp    `json:"updated_at"`
	DeletedAt     pgtype.Timestamp    `json:"deleted_at"`
	ProjectID     pgtype.UUID         `json:"project_id"`
	InvitedUserID pgtype.UUID         `json:"invited_user_id"`
}

type User struct {
	ID           pgtype.UUID      `json:"id"`
	Email        string           `json:"email"`
	Username     string           `json:"username"`
	PhoneNumber  string           `json:"phone_number"`
	PasswordHash string           `json:"password_hash"`
	IsActive     bool             `json:"is_active"`
	FirstName    string           `json:"first_name"`
	LastName     string           `json:"last_name"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	LastLoginAt  pgtype.Timestamp `json:"last_login_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
}
