// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_invites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProjectInvite = `-- name: CreateProjectInvite :one
INSERT INTO project_invites (
    project_id,
    invited_user_id,
    status
) VALUES (
    $1, $2, $3
) RETURNING id, status, created_at, updated_at, deleted_at, project_id, invited_user_id
`

type CreateProjectInviteParams struct {
	ProjectID     pgtype.UUID         `json:"project_id"`
	InvitedUserID pgtype.UUID         `json:"invited_user_id"`
	Status        ProjectInviteStatus `json:"status"`
}

func (q *Queries) CreateProjectInvite(ctx context.Context, arg CreateProjectInviteParams) (ProjectInvite, error) {
	row := q.db.QueryRow(ctx, createProjectInvite, arg.ProjectID, arg.InvitedUserID, arg.Status)
	var i ProjectInvite
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.InvitedUserID,
	)
	return i, err
}

const getProjectInviteByID = `-- name: GetProjectInviteByID :one
SELECT id, status, created_at, updated_at, deleted_at, project_id, invited_user_id FROM project_invites 
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProjectInviteByID(ctx context.Context, id pgtype.UUID) (ProjectInvite, error) {
	row := q.db.QueryRow(ctx, getProjectInviteByID, id)
	var i ProjectInvite
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.InvitedUserID,
	)
	return i, err
}

const hardDeleteInvite = `-- name: HardDeleteInvite :exec
DELETE FROM project_invites WHERE id = $1
`

func (q *Queries) HardDeleteInvite(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteInvite, id)
	return err
}

const listInvitesByProject = `-- name: ListInvitesByProject :many
SELECT id, status, created_at, updated_at, deleted_at, project_id, invited_user_id FROM project_invites 
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListInvitesByProject(ctx context.Context, projectID pgtype.UUID) ([]ProjectInvite, error) {
	rows, err := q.db.Query(ctx, listInvitesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectInvite{}
	for rows.Next() {
		var i ProjectInvite
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProjectID,
			&i.InvitedUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvitesByUser = `-- name: ListInvitesByUser :many
SELECT id, status, created_at, updated_at, deleted_at, project_id, invited_user_id FROM project_invites 
WHERE invited_user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListInvitesByUser(ctx context.Context, invitedUserID pgtype.UUID) ([]ProjectInvite, error) {
	rows, err := q.db.Query(ctx, listInvitesByUser, invitedUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectInvite{}
	for rows.Next() {
		var i ProjectInvite
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProjectID,
			&i.InvitedUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteInvite = `-- name: SoftDeleteInvite :one
UPDATE project_invites SET
    deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, status, created_at, updated_at, deleted_at, project_id, invited_user_id
`

func (q *Queries) SoftDeleteInvite(ctx context.Context, id pgtype.UUID) (ProjectInvite, error) {
	row := q.db.QueryRow(ctx, softDeleteInvite, id)
	var i ProjectInvite
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.InvitedUserID,
	)
	return i, err
}

const updateInviteStatus = `-- name: UpdateInviteStatus :one
UPDATE project_invites SET
    status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, status, created_at, updated_at, deleted_at, project_id, invited_user_id
`

type UpdateInviteStatusParams struct {
	ID     pgtype.UUID         `json:"id"`
	Status ProjectInviteStatus `json:"status"`
}

func (q *Queries) UpdateInviteStatus(ctx context.Context, arg UpdateInviteStatusParams) (ProjectInvite, error) {
	row := q.db.QueryRow(ctx, updateInviteStatus, arg.ID, arg.Status)
	var i ProjectInvite
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.InvitedUserID,
	)
	return i, err
}
